# This is the configuration used to check the rubocop source code.

require:
  - rubocop-rails
  - rubocop-capybara

AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'bin/*'
    - 'db/**/*'
    - 'Guardfile'
Style/Documentation:
  Enabled: false
Rails/DeprecatedActiveModelErrorsMethods:
  Exclude:
    - 'infra/lib/infra/command.rb'
Rails/I18nLocaleTexts:
  Enabled: false

Metrics/BlockLength:
  CountAsOne: ['array', 'heredoc', 'method_call', 'hash']
  Exclude: 
    - 'config/**/*'

Metrics/MethodLength:
  CountAsOne: ['array', 'heredoc', 'method_call', 'hash']

Metrics/AbcSize:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Layout/LineLength:
  Exclude:
    - 'config/initializers/devise.rb'